# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: xcache_cmd.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='xcache_cmd.proto',
  package='',
  serialized_pb=_b('\n\x10xcache_cmd.proto\"\xe8\x04\n\nxcache_cmd\x12!\n\x03\x63md\x18\x01 \x02(\x0e\x32\x14.xcache_cmd.req_type\x12\x12\n\ncontext_id\x18\x02 \x01(\x05\x12\x0b\n\x03\x63id\x18\x03 \x01(\x0c\x12\x0b\n\x03\x64\x61g\x18\x04 \x01(\x0c\x12\x0c\n\x04\x64\x61ta\x18\x05 \x01(\x0c\x12\x0b\n\x03ttl\x18\x06 \x01(\x05\x12\x12\n\ncache_size\x18\x07 \x01(\x05\x12\x14\n\x0c\x63\x61\x63he_policy\x18\x08 \x01(\x05\x12\r\n\x05\x66lags\x18\t \x01(\x05\x12\'\n\x06status\x18\n \x01(\x0e\x32\x17.xcache_cmd.status_type\x12\x12\n\nreadoffset\x18\x0b \x01(\x05\x12\x0f\n\x07readlen\x18\x0c \x01(\x05\x12\x0b\n\x03msg\x18\r \x01(\x0c\"\xa4\x02\n\x08req_type\x12\x19\n\x15XCACHE_FLAG_NOTIFSOCK\x10\x01\x12\x1a\n\x16XCACHE_FLAG_DATASOCKET\x10\x02\x12\x18\n\x14XCACHE_ALLOC_CONTEXT\x10\x03\x12\x10\n\x0cXCACHE_STORE\x10\x04\x12\x13\n\x0fXCACHE_NEWSLICE\x10\x05\x12\x15\n\x11XCACHE_FETCHCHUNK\x10\x07\x12\x12\n\x0eXCACHE_TIMEOUT\x10\x08\x12\x10\n\x0cXCACHE_CLEAR\x10\t\x12\x13\n\x0fXCACHE_RESPONSE\x10\n\x12\x10\n\x0cXCACHE_ERROR\x10\x0b\x12\x15\n\x11XCACHE_GET_STATUS\x10\x0c\x12\x0f\n\x0bXCACHE_READ\x10\r\x12\x14\n\x10XCACHE_SENDCHUNK\x10\x0e\"3\n\x0bstatus_type\x12\r\n\tXCACHE_OK\x10\x01\x12\x15\n\x11XCACHE_ERR_EXISTS\x10\x02\"(\n\x0cxcache_notif\x12\x0b\n\x03\x63md\x18\x01 \x02(\x05\x12\x0b\n\x03\x64\x61g\x18\x02 \x01(\x0c')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_XCACHE_CMD_REQ_TYPE = _descriptor.EnumDescriptor(
  name='req_type',
  full_name='xcache_cmd.req_type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='XCACHE_FLAG_NOTIFSOCK', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='XCACHE_FLAG_DATASOCKET', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='XCACHE_ALLOC_CONTEXT', index=2, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='XCACHE_STORE', index=3, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='XCACHE_NEWSLICE', index=4, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='XCACHE_FETCHCHUNK', index=5, number=7,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='XCACHE_TIMEOUT', index=6, number=8,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='XCACHE_CLEAR', index=7, number=9,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='XCACHE_RESPONSE', index=8, number=10,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='XCACHE_ERROR', index=9, number=11,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='XCACHE_GET_STATUS', index=10, number=12,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='XCACHE_READ', index=11, number=13,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='XCACHE_SENDCHUNK', index=12, number=14,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=292,
  serialized_end=584,
)
_sym_db.RegisterEnumDescriptor(_XCACHE_CMD_REQ_TYPE)

_XCACHE_CMD_STATUS_TYPE = _descriptor.EnumDescriptor(
  name='status_type',
  full_name='xcache_cmd.status_type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='XCACHE_OK', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='XCACHE_ERR_EXISTS', index=1, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=586,
  serialized_end=637,
)
_sym_db.RegisterEnumDescriptor(_XCACHE_CMD_STATUS_TYPE)


_XCACHE_CMD = _descriptor.Descriptor(
  name='xcache_cmd',
  full_name='xcache_cmd',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cmd', full_name='xcache_cmd.cmd', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='context_id', full_name='xcache_cmd.context_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cid', full_name='xcache_cmd.cid', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dag', full_name='xcache_cmd.dag', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data', full_name='xcache_cmd.data', index=4,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ttl', full_name='xcache_cmd.ttl', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cache_size', full_name='xcache_cmd.cache_size', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cache_policy', full_name='xcache_cmd.cache_policy', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='flags', full_name='xcache_cmd.flags', index=8,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='status', full_name='xcache_cmd.status', index=9,
      number=10, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='readoffset', full_name='xcache_cmd.readoffset', index=10,
      number=11, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='readlen', full_name='xcache_cmd.readlen', index=11,
      number=12, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='msg', full_name='xcache_cmd.msg', index=12,
      number=13, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _XCACHE_CMD_REQ_TYPE,
    _XCACHE_CMD_STATUS_TYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=637,
)


_XCACHE_NOTIF = _descriptor.Descriptor(
  name='xcache_notif',
  full_name='xcache_notif',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cmd', full_name='xcache_notif.cmd', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dag', full_name='xcache_notif.dag', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=639,
  serialized_end=679,
)

_XCACHE_CMD.fields_by_name['cmd'].enum_type = _XCACHE_CMD_REQ_TYPE
_XCACHE_CMD.fields_by_name['status'].enum_type = _XCACHE_CMD_STATUS_TYPE
_XCACHE_CMD_REQ_TYPE.containing_type = _XCACHE_CMD
_XCACHE_CMD_STATUS_TYPE.containing_type = _XCACHE_CMD
DESCRIPTOR.message_types_by_name['xcache_cmd'] = _XCACHE_CMD
DESCRIPTOR.message_types_by_name['xcache_notif'] = _XCACHE_NOTIF

xcache_cmd = _reflection.GeneratedProtocolMessageType('xcache_cmd', (_message.Message,), dict(
  DESCRIPTOR = _XCACHE_CMD,
  __module__ = 'xcache_cmd_pb2'
  # @@protoc_insertion_point(class_scope:xcache_cmd)
  ))
_sym_db.RegisterMessage(xcache_cmd)

xcache_notif = _reflection.GeneratedProtocolMessageType('xcache_notif', (_message.Message,), dict(
  DESCRIPTOR = _XCACHE_NOTIF,
  __module__ = 'xcache_cmd_pb2'
  # @@protoc_insertion_point(class_scope:xcache_notif)
  ))
_sym_db.RegisterMessage(xcache_notif)


# @@protoc_insertion_point(module_scope)
