# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: xcache_cache_click.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='xcache_cache_click.proto',
  package='xia',
  serialized_pb=_b('\n\x18xcache_cache_click.proto\x12\x03xia\"i\n\x0excache_message\x12&\n\x04type\x18\x01 \x02(\x0e\x32\x18.xia.xcache_message_type\x12\x0b\n\x03\x63id\x18\x02 \x01(\x0c\x12\x14\n\x0cstart_offset\x18\x03 \x01(\x05\x12\x0c\n\x04\x64\x61ta\x18\x04 \x01(\x0c*J\n\x13xcache_message_type\x12\x0b\n\x07\x43ID_PKT\x10\x01\x12\x10\n\x0c\x44\x45NY_CID_PKT\x10\x02\x12\x14\n\x10\x44\x45NY_CID_ACK_PKT\x10\x03')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_XCACHE_MESSAGE_TYPE = _descriptor.EnumDescriptor(
  name='xcache_message_type',
  full_name='xia.xcache_message_type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CID_PKT', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DENY_CID_PKT', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DENY_CID_ACK_PKT', index=2, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=140,
  serialized_end=214,
)
_sym_db.RegisterEnumDescriptor(_XCACHE_MESSAGE_TYPE)

xcache_message_type = enum_type_wrapper.EnumTypeWrapper(_XCACHE_MESSAGE_TYPE)
CID_PKT = 1
DENY_CID_PKT = 2
DENY_CID_ACK_PKT = 3



_XCACHE_MESSAGE = _descriptor.Descriptor(
  name='xcache_message',
  full_name='xia.xcache_message',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='xia.xcache_message.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cid', full_name='xia.xcache_message.cid', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='start_offset', full_name='xia.xcache_message.start_offset', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data', full_name='xia.xcache_message.data', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=138,
)

_XCACHE_MESSAGE.fields_by_name['type'].enum_type = _XCACHE_MESSAGE_TYPE
DESCRIPTOR.message_types_by_name['xcache_message'] = _XCACHE_MESSAGE
DESCRIPTOR.enum_types_by_name['xcache_message_type'] = _XCACHE_MESSAGE_TYPE

xcache_message = _reflection.GeneratedProtocolMessageType('xcache_message', (_message.Message,), dict(
  DESCRIPTOR = _XCACHE_MESSAGE,
  __module__ = 'xcache_cache_click_pb2'
  # @@protoc_insertion_point(class_scope:xia.xcache_message)
  ))
_sym_db.RegisterMessage(xcache_message)


# @@protoc_insertion_point(module_scope)
