.TH XgetChunkStatus 8 "05 May 2015" "1.0" "XIA Manual Pages"
.SH NAME
XgetChunkStatus \- Get status of chunks.
.SH SYNOPSIS
.nf
.B "#include <xcache.h>"
.sp
.BR "int XgetChunkStatus(int xcacheSock, const char *cid, size_t len);"
.fi

.SH DESCRIPTION
.B XgetChunkStatus()
reads the status of the chunk associated with CID
.I cid.
CID is of length
.I len.
.I xcacheSock
must be a socket allocated by call to
.B XcacheSocket()
function.
.B XgetChunkStatus()
Chunk status can be one of the following:

.B XCS_AVAILABLE
.RS
Chunk is available and ready for read.
.RE
.B XCS_WAITING
.RS
Xcache is waiting for the chunk to be read from the network.
.RE
.B XCS_NOTFOUND
.RS
Chunk is not cached.
.RE

.SH RETURN VALUE
.B XgetChunkStatus()
returns the status of a chunk. In case of error, -1 is returned and
errno is set appropriately.

.SH ERRORS
.B ENOTCONN	
XcacheSock is not connected.

.B EHOSTDOWN	
Xcache is not running.
.B 
.\".SH NOTES

.SH EXAMPLE

See
.B XrequestChunk(8).

.SH SEE ALSO
.B "XopenChunk(8),"
.B "Xput(8),"
.B "Xget(8)"
.SH AUTHOR
Harshad Shirwadkar <harshad@cmu.edu>
