# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import service
from google.protobuf import service_reflection
from google.protobuf import descriptor_pb2


_MSG_MSGTYPE = descriptor.EnumDescriptor(
  name='MsgType',
  full_name='xia.msg.MsgType',
  filename='MsgType',
  values=[
    descriptor.EnumValueDescriptor(
      name='GETLOCALHID', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='GETCID', index=1, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='CONNECTSID', index=2, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='PUTCID', index=3, number=3,
      options=None,
      type=None),
  ],
  options=None,
)


_MSG = descriptor.Descriptor(
  name='msg',
  full_name='xia.msg',
  filename='xia.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='appid', full_name='xia.msg.appid', index=0,
      number=1, type=5, cpp_type=1, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='xid', full_name='xia.msg.xid', index=1,
      number=2, type=12, cpp_type=9, label=1,
      default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='xiapath_src', full_name='xia.msg.xiapath_src', index=2,
      number=5, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='xiapath_dst', full_name='xia.msg.xiapath_dst', index=3,
      number=6, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='payload', full_name='xia.msg.payload', index=4,
      number=3, type=12, cpp_type=9, label=1,
      default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='type', full_name='xia.msg.type', index=5,
      number=4, type=14, cpp_type=8, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
    _MSG_MSGTYPE,
  ],
  options=None)


_MSG_RESPONSE = descriptor.Descriptor(
  name='msg_response',
  full_name='xia.msg_response',
  filename='xia.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='appid', full_name='xia.msg_response.appid', index=0,
      number=1, type=5, cpp_type=1, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='xid', full_name='xia.msg_response.xid', index=1,
      number=2, type=12, cpp_type=9, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='payload', full_name='xia.msg_response.payload', index=2,
      number=3, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_MSG.fields_by_name['type'].enum_type = _MSG_MSGTYPE

class msg(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MSG

class msg_response(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MSG_RESPONSE

