#!/bin/bash

sudo apt-mark hold grub
sudo apt-get update -qq -y
sudo apt-get install -qq -y git net-tools libpq-dev libxml2 libxml2-dev libssl-dev python-pip python-tk python-dev python-requests python-crypto python-scipy build-essential openssl swig

sudo -H pip install pynacl
sudo -H pip install psutil
sudo -H pip install configparser
sudo -H pip install ipaddress

# needed for video broker
sudo -H pip install rpyc
sudo -H pip install msgpack
sudo -H pip install pycountry
sudo -H pip install dotmap
sudo -H pip install simpleplotlib

rel=$(lsb_release -d)

if [[ "$rel" =~ "14" ]]; then
    sudo pip install networkx
    wget http://launchpad.net/ubuntu/+archive/primary/+files/protobuf_2.6.1.orig.tar.gz
    tar xvzf protobuf_2.6.1.orig.tar.gz
    cd protobuf-2.6.1/
    ./configure
    make
    sudo make install
    sudo pip install protobuf==2.6.1
    sudo ldconfig
    cd ..
else
    sudo apt-get install -y python-networkx
    sudo apt-get install -y libprotobuf-dev protobuf-compiler python-protobuf
fi

echo be sure to install gurobi and the required license file if you intent the run the cdn broker
echo http://www.gurobi.com/academia/for-universities

