#!/bin/bash
#
# Copyright 2012 Carnegie Mellon University
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

NAME=`basename $0`
CLICKPATH=../click-2.0
CONFPATH=$CLICKPATH/conf
CLICK=$CLICKPATH/userlevel/click

SINGLE_SCRIPT=xia_chain_topology_socket_reliable_test.click
MULTI_SCRIPT=xia_test_topology_1.click

# default to the standard click script
SCRIPT=$SINGLE_SCRIPT

DEFAULT="(default)"
VERBOSE="1"

help ()
{
	cat << EOH

usage: $NAME [-qvs]
where:
  -q runs click silently
  -v prints click debug messages to stdout (default)
  -s run click using the xia_chain_topology_socket_reliable_test.click
     config file where both client and cserver networks are run on the
	 same machine (default)
  -m run click using the xia_test_topology_1.click config file which
     provides a 4 router network with 6 HIDs and 3 ADs running on a
	 single machine

EOH
	exit 0
}

while getopts ":qvsmh" opt; do
	case $opt in
	    s)
			SCRIPT=$SINGLE_SCRIPT
			DEFAULT=""
			;;
	    m)
			SCRIPT=$MULTI_SCRIPT
			DEFAULT=""
			;;
		q)
			VERBOSE="0"
			;;
		v)
			VERBOSE="1"
			;;
		h)
			help
			;;
		\?)
			printf "\nInvalid option: -$OPTARG\n" >&2
			help
			;;
	esac
done

SNAME=`basename $SCRIPT .click`

if [ ! -f $CONFPATH/$SCRIPT ]; then
	printf "\nERROR: unable to locate click conf file: $SNAME\n\n"
	exit 1
fi

if [ $VERBOSE -eq "0" ]; then
	exec &> /dev/null
fi

printf "\nrunning click using $SNAME $DEFAULT\n\n"

sudo $CLICK -R $CONFPATH/$SCRIPT

