all: 
	make -C dagaddr
	make -C xsocket

static:
	make -C dagaddr static
	make -C xsocket static

clean:
	make -C dagaddr clean
	make -C xsocket clean

test:
	make -C dagaddr test
	make -C xsocket test
